/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#584237',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#8c7164',
        'outline-variant': '#e0c0b1',
        'surface-tint': '#9d4300',
        primary: '#9d4300',
        'on-primary': '#ffffff',
        'primary-container': '#f97316',
        'on-primary-container': '#582200',
        'inverse-primary': '#ffb690',
        secondary: '#006e2f',
        'on-secondary': '#ffffff',
        'secondary-container': '#6bff8f',
        'on-secondary-container': '#007432',
        tertiary: '#006591',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#09a4e8',
        'on-tertiary-container': '#003650',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      boxShadow: {
        card: '0px 4px 20px rgba(0,0,0,0.05)',
        elevated: '0px 8px 30px rgba(0,0,0,0.10)',
      },
    },
  },
  plugins: [],
}
